#!/usr/bin/env bash

###########################
# VARS
HOST="aragorn.fleag.us"
THERE="Work/Ring"
TANK="${HOME}/Google Drive/BACKUP"
GITBASE="${HOME}/GIT"

B=$(tput bold)
R=$(tput setaf 1)
LB=$(tput setaf 6)
N=$(tput sgr0)

[ ! -d "${TANK}" ] && mkdir -p "${TANK}"
###########################


###########################
# IN

#echo -e "\\n ${LB}--- IN ---${N}"

echo "${B}The Villa of Ormen${N}"
rsync --delete -ai aragorn:/usr/local/palermo/Pictures/thevillaoformen/ ${HOME}/Pictures/thevillaoformen/

echo "${B}Local SSH${N}"
rsync -ai ${HOME}/.ssh/ "${TANK}/ssh/LOCAL/"

echo "${B}Jump SSH${N}"
rsync -ai sshjump:.ssh/ "${TANK}/ssh/JUMP/"

echo "${B}Scripts${N}"
rsync -ai ${HOME}/Scripts/ "${TANK}/SCRIPTS/"

echo "${B}Bash${N}"
rsync --exclude .bash_sessions -aqi ${HOME}/.bash* "${TANK}/BASH/"
###########################


###########################
# OUT

#echo -e "\\n${LB}--- OUT ---${N}"

echo "${B}Google${N}"
rsync --exclude .DS_Store --exclude 'Icon*' --exclude 'NoSync' --delete -ai ${HOME}/Google\ Drive palermo@${HOST}:${THERE}/

echo "${B}Git${N}"
GITS="broom-closet directory_utilities docker-common packer splunk-docker"
for GIT in ${GITS} ; do
	rsync --exclude .DS_Store --exclude .git --exclude 'Icon*' --delete -ai ${GITBASE}/${GIT} palermo@${HOST}:${THERE}/
done
###########################
