#!/bin/sh

#--------------
# Where,View,URL,Latitude,Longitude,Timezone,Zipcode

WHERE="Bend"

ALL_THESE_CAMS=" \
	${WHERE},SimpsonPavilion,http://67.210.198.15:8919/cgi-bin/camera?resolution=640,44.047508,-121.323456,US/Pacific,97701 \
	${WHERE},RiverbendPark,http://67.210.198.15:9092/cgi-bin/camera?resolution=640,44.043018,-121.322526,US/Pacific,97701 \
	${WHERE},OldMill,http://67.210.198.15:7271/cgi-bin/camera?resolution=640,44.045987,-121.322958,US/Pacific,97701 \
	${WHERE},Downtown,http://67.210.198.15:8081/cgi-bin/camera?resolution=640,44.057676,-121.313558,US/Pacific,97701 \
	${WHERE},ColoradoDam,http://67.204.164.159:9293/cgi-bin/camera?resolution=640,44.051105,-121.320209,US/Pacific,97701"

#	${WHERE},Airport,http://icons.wunderground.com/webcamramdisk/k/b/kbdn/1/current.jpg,44.093061,-121.202524,US/Pacific"
#--------------

source $HOME/Sources/scripts-git/GetWebcamFunctions
