#!/bin/sh

COUNT=0
SAVEIFS=$IFS
TRANS_LOG="/var/tmp/TransLog.log"
IFS=$(echo -en "\n\b")

echo $(date) >> ${TRANS_LOG}

for TOR in $(sudo /usr/bin/transmission-remote -l | egrep -i "seeding|complete|idle" | sed 's/ \+/ /g') ; do

	ID=$(echo ${TOR} | awk '{print $1}')
	NAME=$(echo ${TOR} | cut -d ' ' -f 11-)

	if [ "${NAME}" ] && [ "${ID}" ] ; then
		echo "Removing ${ID}: ${NAME}"
		echo "Removing ${ID}: ${NAME}" >> ${TRANS_LOG}

		sudo /usr/bin/transmission-remote -t ${ID} -r
	else
		echo "\"${TOR}\" || ${ID}: ${NAME}"
		echo "\"${TOR}\" || ${ID}: ${NAME}" >> ${TRANS_LOG}
	fi
done

IFS=${SAVEIFS}

REMAINING=$(sudo /usr/bin/transmission-remote -l | grep "^ \+[0-9].*")

if [ ! "${REMAINING}" ] ; then
	echo -e "No running Torrents remaining.  Stopping..."
	echo -e "No running Torrents remaining.  Stopping..." >> ${TRANS_LOG}
#	echo 'sudo /etc/init.d/transmission-daemon stop'
#	sudo /etc/init.d/transmission-daemon stop
	echo 'sudo systemctl stop transmission'
	sudo systemctl stop transmission
fi

echo "---------" >> ${TRANS_LOG}

exit

if [ "$1" ] ; then
	echo "Killing exact: \"$1\""
	kill $(ps -e | grep transmission.*${1} | awk '{print $1}')
else
	echo "Killing general: \"$1\""
	kill $(ps -e | grep transmission | awk '{print $1}')
fi
